"""ajout_champs_candidature

Revision ID: a8660364b6cb
Revises: 
Create Date: 2026-05-02 22:11:24.883930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8660364b6cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entreprises_id'), table_name='entreprises')
    op.drop_table('entreprises')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_etudiants_id'), table_name='etudiants')
    op.drop_table('etudiants')
    op.drop_index(op.f('ix_candidatures_id'), table_name='candidatures')
    op.drop_table('candidatures')
    op.drop_index(op.f('ix_offres_stage_id'), table_name='offres_stage')
    op.drop_table('offres_stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offres_stage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('competences_requises', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lieu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gratification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nb_places', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('places_restantes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_limite', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('est_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_publication', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], name=op.f('offres_stage_entreprise_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('offres_stage_pkey'))
    )
    op.create_index(op.f('ix_offres_stage_id'), 'offres_stage', ['id'], unique=False)
    op.create_table('candidatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('etudiant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut', postgresql.ENUM('EN_ATTENTE', 'EN_COURS', 'SELECTIONNE', 'ACCEPTE', 'REFUSE', name='statutcandidature'), autoincrement=False, nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lettre_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commentaires', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_candidature', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['etudiants.id'], name=op.f('candidatures_etudiant_id_fkey')),
    sa.ForeignKeyConstraint(['offre_id'], ['offres_stage.id'], name=op.f('candidatures_offre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('candidatures_pkey'))
    )
    op.create_index(op.f('ix_candidatures_id'), 'candidatures', ['id'], unique=False)
    op.create_table('etudiants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('niveau', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filiere', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('competences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lettre_motivation_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('statut_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], name=op.f('etudiants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('etudiants_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('etudiants_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_etudiants_id'), 'etudiants', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mot_de_passe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'ECOLE', 'ENTREPRISE', 'ETUDIANT', 'ENSEIGNANT', name='roleutilisateur'), autoincrement=False, nullable=False),
    sa.Column('est_actif', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_inscription', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('utilisateurs_pkey'))
    )
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('entreprises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raison_sociale', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secteur', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ville', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_rh_nom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_rh_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site_web', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], name=op.f('entreprises_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entreprises_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('entreprises_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_entreprises_id'), 'entreprises', ['id'], unique=False)
    # ### end Alembic commands ###
